build_image:
   image: docker:stable
   services:
     - docker:dind
       # command: ["--insecure-registry=containers.ligo.org"]
   variables:
     DOCKER_HOST: tcp://docker:2375
     DOCKER_DRIVER: overlay2
   stage: build
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN containers.ligo.org
     - docker build -t containers.ligo.org/daniel-williams/thesis:latest .

