image: docker:git
services:
- docker:dind

variables:
  BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  COMMIT: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  MASTER: $CI_REGISTRY_IMAGE:master
  TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

stages:
    - build
    # - test

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    
build-image-master:
    only:
        - master
    stage: build
    script:
        - docker build --rm --no-cache -t $MASTER  ./
        - docker push $MASTER


build-thesis-pdf:
  image: $MASTER
  stage: build
  script:
    - make pdf
    - mkdir public
    - cp document.pdf public/
  artifacts:
    paths:
    - public

  
